"""Add column bg_image

Revision ID: 241cf8273ce0
Revises: 77144e345587
Create Date: 2022-06-14 12:02:27.948785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '241cf8273ce0'
down_revision = '77144e345587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('background_image_id', sa.String(length=100), nullable=True))
    op.create_foreign_key(op.f('fk_books_background_image_id_images'), 'books', 'images', ['background_image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_books_background_image_id_images'), 'books', type_='foreignkey')
    op.drop_column('books', 'background_image_id')
    # ### end Alembic commands ###
