"""add on delete cascade for selections

Revision ID: 5a50de9a8207
Revises: 9d51cf34f587
Create Date: 2022-06-21 15:21:09.209911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a50de9a8207'
down_revision = '9d51cf34f587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_selections_user_id_users', 'selections', type_='foreignkey')
    op.create_foreign_key(op.f('fk_selections_user_id_users'), 'selections', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_selections_user_id_users'), 'selections', type_='foreignkey')
    op.create_foreign_key('fk_selections_user_id_users', 'selections', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
