"""Add column created_at to Book

Revision ID: 77144e345587
Revises: cc1ef7e38328
Create Date: 2022-06-13 19:42:04.014083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77144e345587'
down_revision = 'cc1ef7e38328'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'created_at')
    # ### end Alembic commands ###
